FORMAT: 3A
HOST: http://epic-mail-2019.herokuapp.com/api/v1/

# EPIC MAIL

This is a web application that allows messages to be exchanged over the internet


# Allowed HTTPs requests:
* POST    : Update resource
* GET     : Get a resource or list of resources
* DELETE  : To delete resource

# Description Of Usual Server Responses:
* 200 ``OK`` - the request was successful (some API calls may return 201 instead).
* 201 ``created`` - the request was successful and a resource was created.
* 404 ``Not found`` -  resource was not found.

# Code Sample 
``` 
{
 status: Server Responses,
 data: [array] or {objects}
}

```

## HOME [/]
### Homepage [GET]
+ Response 200 (application/json)
               
               {
               "message": "Welcome to the api"
               }

## User [/auth/]
### Create a new User [POST]
You should  create an account to use this service with your credentials.

+ Request (application/json)

        {
            "firstName": "Favourite programming language?",
            "lastName": "Ipsum",
            "email": "amajag@hshsh.com"
            "password": "X-X-X-X"
            
            
        }
        
+ Response 201 (application/json)
        
    + Headers

            Location: /auth/signup
    
    + Body 
            
            {
            "status": 201,
            "token": "453hegu3yeuaysuyewuuywuuw2u734hudhdvvchczgzhjwu7837287gdg"
            
            }
            
## Messages [/messages]

### List All Received Messages  In Inbox[GET]
User should be able to retrieve all messages received 
## Message Status (enum[number])

+ `0` - Draft
+ `1` - read
+ `2` - unread
+ `3` - sent


+ Response 200 (application/json)
    
    + Headers 
            
            Location: /messages 
            
    
            
    + Body

            {
                "status": 200
                "data":[
                    {
                        "id ": Integer,
                        "createdOn": DateTime,
                        "subject": String,
                        "message": String,
                        "senderId": String,
                        "receiverId": String,
                        "parentMessageId":String,
                        "status": `1` (Message Status)
                    }, 
                ]
            }