
            "email": "amajag@hshsh.com"
            "password": "X-X-X-X"
            
            
        }
        
+ Response 201 (application/json)
        
    + Headers

            Location: /auth/signup
    
    + Body 
            
            {
            "status": 201,
            "token": "453hegu3yeuaysuyewuuywuuw2u734hudhdvvchczgzhjwu7837287gdg"
            
            }


### Login a User [POST/auth/login]

+ Request (application/json)
    
    
   + Body 
            
    
        {
            
            "email":" <invalid-email> or <non-existent user>",
            "password": "<incorrect-password> or <empty-password-field>"
        }
        
        
            
        
            
+ Response 404 (application/json) 
            
   + Body

            {
                "error": 404
                "error": "empty input fields or user does not exist"
            }
            
            

+ Request (application/json)
    
    
   + Body 
            
    
        {
            
            "email":"somegoodemail@email.com"
            "password": "correctpasswprd"
        }
        

+ Response 200 (application/json)
    
  
            
    
            
    + Body

            {
                "status": 200
                "token": "dhbcsbvyuebyu3444534jhbabc3982"
                ]
            }
            
            
            
            
## Messages [/messages]

### Get All Received Messages  In Inbox[GET]
User should be able to retrieve all messages received 


+ Response 200 (application/json)
    
    + Headers 
            
            Location: /messages 
            
    
            
    + Body

            {
                "status": 200
                "data":[
                    {
                        "id ": Integer,
                        "createdOn": DateTime,
                        "subject": String,

            }